name: Build and Test - iOS 14.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '12.0' }}
    steps:
    - uses: actions/checkout@v2
    - name: Generate Mockingbird Mocks
      run: Pods/MockingbirdFramework/mockingbird generate --targets 'Hymns'  --outputs 'MockingbirdMocks/HymnsMocks.generated.swift' --disable-swiftlint
    - name: Select latest xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    # While we can actually do both the build and test step in one with "xcodebuild test", it is slower and ends up with a very hard to read 3000 line report.
    # # https://medium.com/xcblog/xcodebuild-deploy-ios-app-from-command-line-c6defff0d8b8
    # So it is faster to break it up into two steps. Build and test. Also, useful if we choose to have more than one kind of test.
    - name: Build for Testing
      run: xcodebuild build-for-testing -workspace Hymns.xcworkspace -scheme Hymns -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.0"
    # Very important to know that -testPlan is a flag that uses an xCode test plan of choice. Only necessary if we are going to use testplans.
    - name: Test with MasterTestPlan
      run: xcodebuild test-without-building -workspace Hymns.xcworkspace -scheme Hymns -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.0" -testPlan MasterTestPlan
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Test Logs
        path: /Users/runner/Library/Developer/Xcode/DerivedData/Hymns-*/Logs
